const kanjiData = [
  { kanji: "愛人", meaningJP: "情人、外遇", meaningCN: "配偶、爱人" },
  { kanji: "床", meaningJP: "地面、地板", meaningCN: "床铺" },
  { kanji: "迷惑", meaningJP: "添麻烦", meaningCN: "困惑、迷茫" },
  { kanji: "手紙", meaningJP: "书信、信件", meaningCN: "卫生纸" },
  { kanji: "階段", meaningJP: "楼梯、台阶", meaningCN: "发展阶段" },
  { kanji: "汽車", meaningJP: "火车", meaningCN: "汽车" },
  { kanji: "留守", meaningJP: "不在家", meaningCN: "看守、留守" },
  { kanji: "真面目", meaningJP: "认真、老实", meaningCN: "本来面目" },
  { kanji: "無理", meaningJP: "勉强、做不到", meaningCN: "没有道理" },
  { kanji: "勝手", meaningJP: "擅自、随便", meaningCN: "随心所欲" },
  { kanji: "内緒", meaningJP: "秘密", meaningCN: "内部关系" },
  { kanji: "小人", meaningJP: "小孩、儿童", meaningCN: "品行不好的人" },
  { kanji: "大家", meaningJP: "房东、屋主", meaningCN: "大家、众人" },
  { kanji: "お得意", meaningJP: "常客、老主顾", meaningCN: "得意、骄傲" },
  { kanji: "不始末", meaningJP: "不小心、马虎", meaningCN: "没有始末" },
  { kanji: "お辞儀", meaningJP: "鞠躬、行礼", meaningCN: "告辞、仪式" },
  { kanji: "遠慮", meaningJP: "客气、推辞", meaningCN: "长远考虑" },
  { kanji: "面倒", meaningJP: "麻烦、费事", meaningCN: "面面俱到" },
  { kanji: "見学", meaningJP: "参观、观摩", meaningCN: "学习、研究" },
  { kanji: "講義", meaningJP: "课程、讲课", meaningCN: "讲义、文稿" },
  { kanji: "採用", meaningJP: "录用、聘用", meaningCN: "采纳、采用" },
  { kanji: "検討", meaningJP: "斟酌、讨论", meaningCN: "深入研究" },
  { kanji: "経理", meaningJP: "会计、财务", meaningCN: "经营管理" },
  { kanji: "総務", meaningJP: "行政、总务", meaningCN: "总管事务" },
  { kanji: "人事", meaningJP: "人力资源", meaningCN: "人的事情" },
  { kanji: "報告", meaningJP: "汇报、报告", meaningCN: "告诉、告知" },
  { kanji: "連絡", meaningJP: "联系、联络", meaningCN: "连续、脉络" },
  { kanji: "手続", meaningJP: "手续、程序", meaningCN: "办理步骤" },
  { kanji: "予定", meaningJP: "计划、安排", meaningCN: "预定、预订" },
  { kanji: "期限", meaningJP: "截止日期", meaningCN: "时间限制" },
  { kanji: "状況", meaningJP: "情况、状况", meaningCN: "状态、情形" },
  { kanji: "結果", meaningJP: "结局、结果", meaningCN: "最终果实" },
  { kanji: "影響", meaningJP: "影响、作用", meaningCN: "影子、声响" },
  { kanji: "関係", meaningJP: "关系、关联", meaningCN: "关联系统" },
  { kanji: "構造", meaningJP: "结构、构造", meaningCN: "构筑造型" },
  { kanji: "機能", meaningJP: "功能、作用", meaningCN: "机器能力" },
  { kanji: "芸術", meaningJP: "艺术、文艺", meaningCN: "技艺、法术" },
  { kanji: "衛生", meaningJP: "卫生、保洁", meaningCN: "养生、保健" },
  { kanji: "勉強", meaningJP: "学习、用功", meaningCN: "勉强、将就" },
  { kanji: "新聞", meaningJP: "报纸", meaningCN: "新闻、消息" },
  { kanji: "時計", meaningJP: "钟表、手表", meaningCN: "计时仪器" },
  { kanji: "看板", meaningJP: "招牌、广告牌", meaningCN: "木板、牌子" },
  { kanji: "番組", meaningJP: "电视节目、节目", meaningCN: "一组、一套" },
  { kanji: "人形", meaningJP: "玩偶、人偶", meaningCN: "人的形态" },
  { kanji: "洋服", meaningJP: "西装、正装", meaningCN: "西洋衣服" },
  { kanji: "自腹", meaningJP: "自己掏钱、自费", meaningCN: "自己的肚子" },
  { kanji: "好物", meaningJP: "爱吃的食物、嗜好品", meaningCN: "优质物品" },
  { kanji: "相棒", meaningJP: "搭档、伙伴", meaningCN: "好的棍棒" },
  { kanji: "表札", meaningJP: "门牌、户牌", meaningCN: "信件、札记" },
  { kanji: "湯", meaningJP: "热水、温泉", meaningCN: "汤水、soup" },
  { kanji: "野菜", meaningJP: "蔬菜", meaningCN: "野生植物" },
  { kanji: "果物", meaningJP: "水果", meaningCN: "果实" },
  { kanji: "台所", meaningJP: "厨房", meaningCN: "台子、处所" },
  { kanji: "風呂", meaningJP: "澡堂、洗澡", meaningCN: "风池" },
  { kanji: "小売", meaningJP: "零售、零卖", meaningCN: "小买卖" },
  { kanji: "両替", meaningJP: "兑换货币、换钱", meaningCN: "两边交换" },
  { kanji: "本棚", meaningJP: "书架、书柜", meaningCN: "书本架子" },
  { kanji: "茶碗", meaningJP: "饭碗、小碗", meaningCN: "茶杯子" },
  { kanji: "草履", meaningJP: "拖鞋、草屐", meaningCN: "草鞋" },
  { kanji: "旅券", meaningJP: "护照", meaningCN: "旅行券" },
  { kanji: "金具", meaningJP: "金属配件、五金", meaningCN: "金属工具" },
  { kanji: "建具", meaningJP: "门窗配件、装修件", meaningCN: "建筑工具" },
  { kanji: "割引", meaningJP: "打折、折扣", meaningCN: "强行拉回" },
  { kanji: "見本", meaningJP: "样品、样本", meaningCN: "亲眼所见" },
  { kanji: "景品", meaningJP: "赠品、礼品", meaningCN: "奖品" },
  { kanji: "売店", meaningJP: "小卖部、便利店", meaningCN: "卖掉店铺" },
  { kanji: "駅弁", meaningJP: "车站便当", meaningCN: "车站文官" },
  { kanji: "定食", meaningJP: "套餐、份饭", meaningCN: "固定食物" },
  { kanji: "部屋", meaningJP: "房间", meaningCN: "房屋整体" },
  { kanji: "周囲", meaningJP: "周围、周边", meaningCN: "四周范围" },
  { kanji: "当面", meaningJP: "目前、暂时", meaningCN: "当面见面" },
  { kanji: "途中", meaningJP: "半路、途中", meaningCN: "过程当中" },
  { kanji: "郊外", meaningJP: "郊区", meaningCN: "城外" },
  { kanji: "都合", meaningJP: "情况、方便与否", meaningCN: "城市格局" },
  { kanji: "境内", meaningJP: "神社院内", meaningCN: "国境之内" },
  { kanji: "屋上", meaningJP: "屋顶、楼顶", meaningCN: "房屋上方" },
  { kanji: "地下", meaningJP: "地下室、地铁", meaningCN: "地面之下" },
  { kanji: "通路", meaningJP: "通道、过道", meaningCN: "打通道路" },
  { kanji: "玄関", meaningJP: "门口、玄关", meaningCN: "玄妙关口" },
  { kanji: "裏口", meaningJP: "后门", meaningCN: "里面的入口" },
  { kanji: "出口", meaningJP: "检票口、出口", meaningCN: "出去的路口" },
  { kanji: "入口", meaningJP: "检票口、入口", meaningCN: "进入的路口" },
  { kanji: "空地", meaningJP: "空地、荒地", meaningCN: "空闲土地" },
  { kanji: "平地", meaningJP: "平原、平坦地", meaningCN: "平整地面" },
  { kanji: "高地", meaningJP: "山区、高地", meaningCN: "高处地带" },
  { kanji: "沿岸", meaningJP: "海边、沿岸", meaningCN: "沿着岸边" },
  { kanji: "中心", meaningJP: "市中心、核心", meaningCN: "正中心" },
  { kanji: "方面", meaningJP: "地区、领域", meaningCN: "方方面面" },
  { kanji: "地元", meaningJP: "本地、家乡", meaningCN: "土地源头" },
  { kanji: "本場", meaningJP: "原产地、正宗产地", meaningCN: "本来场地" },
  { kanji: "近所", meaningJP: "邻居、附近", meaningCN: "近处住所" },
  { kanji: "休業", meaningJP: "停业、休息", meaningCN: "休假" },
  { kanji: "出勤", meaningJP: "上班", meaningCN: "外出办事" },
  { kanji: "退社", meaningJP: "下班、离职", meaningCN: "辞职" },
  { kanji: "残業", meaningJP: "加班", meaningCN: "剩余业务" },
  { kanji: "辞書", meaningJP: "词典、字典", meaningCN: "辞职文书" },
  { kanji: "書籍", meaningJP: "图书、书籍", meaningCN: "书写书籍" },
  { kanji: "実習", meaningJP: "实习", meaningCN: "实际学习" },
  { kanji: "研修", meaningJP: "进修、培训", meaningCN: "研究修习" },
  { kanji: "先輩", meaningJP: "学长、学姐、前辈", meaningCN: "前辈" },
  { kanji: "後輩", meaningJP: "学弟、学妹、后辈", meaningCN: "后辈" },
  { kanji: "担当", meaningJP: "负责、担当", meaningCN: "担任岗位" },
  { kanji: "役員", meaningJP: "高管、董事", meaningCN: "工作人员" },
  { kanji: "社長", meaningJP: "老板、社长", meaningCN: "社长" },
  { kanji: "会長", meaningJP: "董事长", meaningCN: "会长" },
  { kanji: "事務", meaningJP: "办公、事务", meaningCN: "事务" },
  { kanji: "業務", meaningJP: "工作、业务", meaningCN: "职业事务" },
  { kanji: "休暇", meaningJP: "假期", meaningCN: "空闲时间" },
  { kanji: "休日", meaningJP: "休息日", meaningCN: "休假日子" },
  { kanji: "出張", meaningJP: "出差", meaningCN: "出去张扬" },
  { kanji: "転勤", meaningJP: "调岗、调动", meaningCN: "转动勤奋" },
  { kanji: "辛抱", meaningJP: "忍耐、忍受", meaningCN: "拥抱" },
  { kanji: "我慢", meaningJP: "忍耐、克制", meaningCN: "缓慢" },
  { kanji: "厚生", meaningJP: "福利、保障", meaningCN: "优厚对待" },
  { kanji: "機嫌", meaningJP: "心情、情绪", meaningCN: "机会" },
  { kanji: "不機嫌", meaningJP: "不高兴、不悦", meaningCN: "没有机会" },
  { kanji: "元気", meaningJP: "健康、精神", meaningCN: "原本气息" },
  { kanji: "安心", meaningJP: "放心、安心", meaningCN: "安全心意" },
  { kanji: "用心", meaningJP: "小心、提防", meaningCN: "专心" },
  { kanji: "断念", meaningJP: "放弃、死心", meaningCN: "念头中断" },
  { kanji: "了解", meaningJP: "同意、明白", meaningCN: "了解情况" },
  { kanji: "奇特", meaningJP: "难得、可贵", meaningCN: "奇怪、特别" },
  { kanji: "多少", meaningJP: "稍微、一些", meaningCN: "数量多少" },
  { kanji: "全然", meaningJP: "完全（否定）", meaningCN: "全部" },
  { kanji: "比較", meaningJP: "相当、比较", meaningCN: "对比" },
  { kanji: "相当", meaningJP: "差不多、相当", meaningCN: "非常" },
  { kanji: "優先", meaningJP: "优先", meaningCN: "优秀首先" },
  { kanji: "気分", meaningJP: "心情、情绪", meaningCN: "气氛" },
  { kanji: "気持", meaningJP: "心情、感受", meaningCN: "心情" },
  { kanji: "苦労", meaningJP: "辛苦、操劳", meaningCN: "劳苦" },
  { kanji: "不安", meaningJP: "担心、不安", meaningCN: "不安全" },
  { kanji: "不便", meaningJP: "不方便", meaningCN: "不便利" },
  { kanji: "失礼", meaningJP: "告辞、打扰、对不起", meaningCN: "没有礼貌" },
  { kanji: "丁寧", meaningJP: "礼貌、周到", meaningCN: "仔细" },
  { kanji: "穏やか", meaningJP: "平稳、温和", meaningCN: "温和" },
  { kanji: "健闘", meaningJP: "努力、奋战", meaningCN: "健康奋斗" },
  { kanji: "感心", meaningJP: "佩服、赞叹", meaningCN: "关心" },
  { kanji: "引取", meaningJP: "领取、带回", meaningCN: "吸引" },
  { kanji: "帰宅", meaningJP: "回家", meaningCN: "回到宅邸" },
  { kanji: "上達", meaningJP: "进步、提高", meaningCN: "向上到达" },
  { kanji: "受取", meaningJP: "接收、领取", meaningCN: "接受获取" },
  { kanji: "返事", meaningJP: "回复、回信", meaningCN: "返还事情" },
  { kanji: "出会", meaningJP: "偶遇、相遇", meaningCN: "出来见面" },
  { kanji: "注意", meaningJP: "小心、提醒", meaningCN: "关注" },
  { kanji: "用意", meaningJP: "准备", meaningCN: "用心思考" },
  { kanji: "発見", meaningJP: "发现、找到", meaningCN: "发现" },
  { kanji: "発表", meaningJP: "公布、发表", meaningCN: "发表" },
  { kanji: "案内", meaningJP: "向导、引导", meaningCN: "内部方案" },
  { kanji: "送別", meaningJP: "送行、送别", meaningCN: "告别" },
  { kanji: "到着", meaningJP: "抵达、到达", meaningCN: "到达着陆" },
  { kanji: "発生", meaningJP: "发生、产生", meaningCN: "产生" },
  { kanji: "完成", meaningJP: "完成、做成", meaningCN: "完全成功" },
  { kanji: "利用", meaningJP: "使用、利用", meaningCN: "利益用处" },
  { kanji: "予約", meaningJP: "预订、预约", meaningCN: "预先约定" },
  { kanji: "応募", meaningJP: "报名、应征", meaningCN: "响应招募" },
  { kanji: "応援", meaningJP: "加油、支持", meaningCN: "响应支援" },
  { kanji: "通行", meaningJP: "通行、通过", meaningCN: "通过行走" },
  { kanji: "走行", meaningJP: "行驶", meaningCN: "跑步前行" },
  { kanji: "移動", meaningJP: "移动、挪动", meaningCN: "移动" },
  { kanji: "変更", meaningJP: "更改、变更", meaningCN: "变化更换" },
  { kanji: "修理", meaningJP: "维修、修理", meaningCN: "修整治理" },
  { kanji: "掃除", meaningJP: "打扫、清扫", meaningCN: "清除" },
  { kanji: "整理", meaningJP: "收拾、整理", meaningCN: "整顿治理" },
  { kanji: "片付", meaningJP: "收拾、整理", meaningCN: "分片放置" },
  { kanji: "支払", meaningJP: "支付、付款", meaningCN: "支付" },
  { kanji: "返金", meaningJP: "退款、还钱", meaningCN: "归还金钱" },
  { kanji: "販売", meaningJP: "销售、售卖", meaningCN: "贩卖" },
  { kanji: "購入", meaningJP: "购买、购入", meaningCN: "购入" },
  { kanji: "試験", meaningJP: "考试、测试", meaningCN: "试验" },
  { kanji: "試用", meaningJP: "试用、试穿", meaningCN: "尝试使用" },
  { kanji: "投票", meaningJP: "投票、表决", meaningCN: "投放票据" },
  { kanji: "記入", meaningJP: "填写、写入", meaningCN: "记录进入" },
  { kanji: "提出", meaningJP: "提交、递交", meaningCN: "拿出" },
  { kanji: "連休", meaningJP: "长假、连续假期", meaningCN: "连续休息" },
  { kanji: "延期", meaningJP: "推迟、延期", meaningCN: "延长日期" },
  { kanji: "中止", meaningJP: "取消、中止", meaningCN: "中途停止" },
  { kanji: "先月", meaningJP: "上个月", meaningCN: "本月初" },
  { kanji: "来月", meaningJP: "下个月", meaningCN: "本月末" },
  { kanji: "右手", meaningJP: "右手、得力助手", meaningCN: "右边的手" },
  { kanji: "左手", meaningJP: "左手、副手", meaningCN: "左边的手" },
  { kanji: "万年", meaningJP: "长久、永久", meaningCN: "一万年" },
  { kanji: "当日", meaningJP: "当天、当日", meaningCN: "当日" },
  { kanji: "後日", meaningJP: "改天、日后", meaningCN: "日后" },
  { kanji: "近日", meaningJP: "最近、近日", meaningCN: "临近日子" },
  { kanji: "平日", meaningJP: "工作日", meaningCN: "平常日子" },
  { kanji: "深夜", meaningJP: "深夜、凌晨", meaningCN: "深深夜晚" },
  { kanji: "早朝", meaningJP: "清晨、一早", meaningCN: "早早早晨" },
  { kanji: "以前", meaningJP: "以前、过去", meaningCN: "以前" },
  { kanji: "以後", meaningJP: "今后、之后", meaningCN: "以后" },
  { kanji: "以外", meaningJP: "除了、以外", meaningCN: "外面" },
  { kanji: "以内", meaningJP: "以内、之内", meaningCN: "里面" },
  { kanji: "以上", meaningJP: "超过、以上", meaningCN: "上面" },
  { kanji: "以下", meaningJP: "低于、以下", meaningCN: "下面" },
  { kanji: "別途", meaningJP: "另外、另行", meaningCN: "别的路途" },
  { kanji: "同様", meaningJP: "同样、一样", meaningCN: "同样" },
  { kanji: "各種", meaningJP: "各种、各类", meaningCN: "各类种子" },
  { kanji: "複数", meaningJP: "多个、复数", meaningCN: "复杂数字" },
  { kanji: "単数", meaningJP: "单个、单数", meaningCN: "单纯数字" },
  { kanji: "実物", meaningJP: "实物、真品", meaningCN: "真实物品" },
  { kanji: "現物", meaningJP: "现货、实物", meaningCN: "现有物品" },
  { kanji: "無料", meaningJP: "免费", meaningCN: "没有费用" },
  { kanji: "有料", meaningJP: "收费", meaningCN: "有费用" },
  { kanji: "半額", meaningJP: "半价", meaningCN: "一半金额" },
  { kanji: "全額", meaningJP: "全额、全款", meaningCN: "全部金额" },
  { kanji: "割合", meaningJP: "比例、比率", meaningCN: "分割合并" }
];

const kataAttachData = [
  { katakana: "は", meaning: "提示主语（谁 / 什么）", exampleJP: "私は本を読みます", exampleCN: "我看书" },
  { katakana: "が", meaning: "强调主语、小主语", exampleJP: "雨が降る／彼が好きです", exampleCN: "下雨了／我喜欢他" },
  { katakana: "を", meaning: "提示宾语（做什么）", exampleJP: "本を読む／コーヒーを飲む", exampleCN: "看书／喝咖啡" },
  { katakana: "の", meaning: "表所属（的）", exampleJP: "私の本／会社の規則", exampleCN: "我的书／公司的规定" },
  { katakana: "に", meaning: "地点 / 方向 / 对象（在 / 向 / 给）", exampleJP: "家に帰る／友達に送る／3 時に会う", exampleCN: "回家／给朋友送（东西）／3 点见面" },
  { katakana: "で", meaning: "地点 / 方式（在… 地方 / 用…）", exampleJP: "公園で遊ぶ／ペンで書く／車で行く", exampleCN: "在公园玩／用钢笔写／开车去" },
  { katakana: "と", meaning: "和… 一起 / 列举 / 引用", exampleJP: "友達と行く／りんごとバナナ／「好き」と言う", exampleCN: "和朋友去／苹果和香蕉／说 “喜欢”" },
  { katakana: "へ", meaning: "方向（去往…）", exampleJP: "東京へ行く／学校へ向かう", exampleCN: "去东京／朝学校走去" },
  { katakana: "から", meaning: "从…（时间 / 地点 / 来源）", exampleJP: "9 時から／学校から帰る／彼から聞く", exampleCN: "从 9 点开始／从学校回家／听他说" },
  { katakana: "まで", meaning: "到… 为止（时间 / 地点）", exampleJP: "5 時まで／駅まで歩く", exampleCN: "到 5 点为止／走到车站" },
  { katakana: "も", meaning: "也", exampleJP: "私も行く／彼も学生です", exampleCN: "我也去／他也是学生" },
  { katakana: "より", meaning: "比…/ 与其… 不如", exampleJP: "彼より高い／本より映画が好き", exampleCN: "比他高／比起书更喜欢电影" },
  { katakana: "ほど", meaning: "程度（… 左右 / 像… 一样）", exampleJP: "日本ほど小さい／3 時間ほどかかる", exampleCN: "像日本一样小／花费 3 小时左右" },
  { katakana: "か", meaning: "疑问（吗 / 是否）/ 不确定", exampleJP: "行くか？／誰か来た", exampleCN: "去吗？／有人来了" },
  { katakana: "ので", meaning: "原因（因为，普通口语）", exampleJP: "雨が降るので、行かない", exampleCN: "因为下雨，所以不去" },
  { katakana: "ため", meaning: "原因（因为，正式）/ 为了", exampleJP: "仕事のため遅刻／健康のため運動", exampleCN: "因为工作迟到／为了健康运动" },
  { katakana: "ば", meaning: "如果（假设）", exampleJP: "雨が降れば、行かない", exampleCN: "如果下雨，就不去" },
  { katakana: "とき", meaning: "… 的时候", exampleJP: "食事をするとき／休みのとき", exampleCN: "吃饭的时候／休息的时候" },
  { katakana: "間", meaning: "… 期间（持续）", exampleJP: "仕事の間／雨が降っている間", exampleCN: "工作期间／下雨的期间" },
  { katakana: "以外", meaning: "除了… 之外", exampleJP: "彼以外、誰も知らない", exampleCN: "除了他，没人知道" },
  { katakana: "以内", meaning: "在… 之内", exampleJP: "3 日以内に返す", exampleCN: "3 天内归还" },
  { katakana: "以上", meaning: "超过 / 以上", exampleJP: "10 人以上／高校卒業以上", exampleCN: "10 人以上／高中以上学历" },
  { katakana: "以下", meaning: "低于 / 以下", exampleJP: "5 歳以下／1 万円以下", exampleCN: "5 岁以下／1 万日元以下" },
  { katakana: "別途", meaning: "另外、另行", exampleJP: "別途連絡する", exampleCN: "另行联系" },
  { katakana: "同様", meaning: "同样、一样", exampleJP: "彼と同様の意見", exampleCN: "和他同样的意见" },
  { katakana: "各種", meaning: "各种、各类", exampleJP: "各種商品を取り扱う", exampleCN: "经营各种商品" },
  { katakana: "複数", meaning: "多个、复数", exampleJP: "複数の人が参加", exampleCN: "多个人参加" },
  { katakana: "単数", meaning: "单个、单数", exampleJP: "単数の回答を求める", exampleCN: "要求单个回答" },
  { katakana: "ます", meaning: "动词礼貌结尾", exampleJP: "行く→行きます／食べる→食べます", exampleCN: "去→去（礼貌）／吃→吃（礼貌）" },
  { katakana: "です", meaning: "形容词 / 名词礼貌结尾", exampleJP: "高い→高いです／学生→学生です", exampleCN: "高→高（礼貌）／学生→是学生" },
  { katakana: "ない", meaning: "否定（不…）", exampleJP: "行く→行かない／食べる→食べない", exampleCN: "不去／不吃" },
  { katakana: "ません", meaning: "礼貌否定（不…）", exampleJP: "行く→行きません／食べる→食べません", exampleCN: "不去（礼貌）／不吃（礼貌）" },
  { katakana: "た", meaning: "过去式（… 了）", exampleJP: "行く→行った／食べる→食べた", exampleCN: "去了／吃了" },
  { katakana: "ました", meaning: "礼貌过去式（… 了）", exampleJP: "行く→行きました／食べる→食べました", exampleCN: "去了（礼貌）／吃了（礼貌）" },
  { katakana: "たい", meaning: "想要…（主语是自己）", exampleJP: "食べる→食べたい／行く→行きたい", exampleCN: "想吃／想去" },
  { katakana: "たがる", meaning: "想要…（主语是别人）", exampleJP: "彼は食べたがる／友達は", exampleCN: "" }
];